version: "3"

services:
  ###############################################
  # Frontend: The Frontend service
  ###############################################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    hostname: frontend
    restart: always
    ports:
      - "3000:3000"

  ##############################################
  # Backend: The Backend service
  ##############################################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    shm_size: '2gb'
    hostname: backend
    restart: always
    ports:
      - "5000:5000"